name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18.x'
                registry-url: 'https://registry.npmjs.org'
            
            - run: npm ci
            - run: npm run lint
            - name: npm run unit-test
              run: |
                npm run unit-test
                sed -i 's/\/home\/runner\/work\/flood-webchat\/flood-webchat\//\/github\/workspace\//g' coverage/lcov.info

            - name: sonarcloud
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: >
                  -Dsonar.organization=defra
                  -Dsonar.projectKey=DEFRA_flood-webchat
                  -Dsonar.sources=src
                  -Dsonar.exclusions=**/node_modules/**,**/__tests__/**
                  -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
                  -Dsonar.javascript.exclusions=**/node_modules/**,**/_tests_/**
