name: Publish to NPM
on:
  release:
    types:
      - published
jobs:
  version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm ci
      - name: compile templates
        run: npm run compile-templates
      - name: version & publish
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          IS_PRE_RELEASE="${{ github.event.release.pre_release }}"
          VERSION_PATTERN="^v([0-9]{1,}.[0-9]{1,}.[0-9]{1,})(-[0-9A-Za-z-].*)?$"
          PRE_RELEASE_PATTERN="(-[0-9A-Za-z-].*)$"
          
          if ! [[ "$TAG_NAME" =~ $VERSION_PATTERN ]]; then
            echo FAILED TO MATCH VERSION_PATTERN
            exit 1
          fi
          
          if [[ "$IS_PRE_RELEASE" == "true" ]] || [[ "$TAG_NAME" =~ $PRE_RELEASE_PATTERN ]]; then
            RELEASE_TAG="pre-release"
          else
            RELEASE_TAG="latest"
          fi
          npm version --no-git-tag-version "${TAG_NAME}"
          npm publish --access public --tag="${RELEASE_TAG}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
